apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 431767255371.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 431767255371.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: "50875350"
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
